apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tmall
  namespace: cad-t4
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/tmall/`)
      kind: Rule
      services:
        - name: tmall-frontend
          port: 80
